services:
  web:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
